" We are using vim, not vi
set nocompatible

filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" My Bundles here:
" original repos on github
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-markdown'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'altercation/vim-colors-solarized'
Plugin 'sickill/vim-monokai'
Plugin 'dracula/vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'fatih/vim-go'
Plugin 'mileszs/ack.vim'
Plugin 'chriskempson/vim-tomorrow-theme'
"Plugin 'derekwyatt/vim-scala'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'klen/python-mode'
"Plugin 'davidhalter/jedi-vim'
"Plugin 'majutsushi/tagbar'

filetype plugin indent on

set laststatus=2

" Rebind <leader> key
let mapleader = ","

set modeline

" Backup
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

set backspace=indent,eol,start
set mouse=a
set noerrorbells
set wildmenu

" UI
set cursorline
set linespace=0
" hilight matching braces
set showmatch
set matchtime=5
set nostartofline
set ruler
" how many commands are kept in history
set history=100

" Search
set hlsearch    " hilight search
set incsearch   " incremental search
set ignorecase  " case insensitive
set smartcase   " unless search term has capital letters
nnoremap n nzz

" Indentation
set cindent
set smartindent
set autoindent
set tabstop=4       " how many columns one tab is
set shiftwidth=4    " how many columns text is indented with reindent operators
set softtabstop=8   " how many columns is used when tab is hit in insert mode
set noexpandtab     " let's use real tabs (set expandtab to add spaces)
set smarttab

" Text formatting
set expandtab
set ignorecase
set smartcase
set gdefault
set wrap
set textwidth=78
set formatoptions=qrn1

set encoding=utf-8
"set list listchars=tab:»»,trail:-,extends:>,precedes:<,eol:¬

" Move between windows
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Move between tabs
map <leader>n <esc>:tabprevious<CR>
map <leader>m <esc>:tabnext<CR>

" Better indentation
vnoremap < <gv
vnoremap > >gv

" Hidden chars
set listchars=tab:▸\ ,eol:¬

" hilight trailing spaces
:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/


" Markdown mode
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

"""""""""""
" Plugins "
"""""""""""
" autocmd vimenter * NERDTree
"
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif


"theme
set t_Co=256
syntax on

"theme
set background=dark
"colorscheme dracula
colorscheme solarized
