autoload -U compinit promptinit
compinit
promptinit

# This will set the default prompt to the walters theme
prompt walters

PATH=$PATH:/opt/android-sdk/tools
PATH=$PATH:$HOME/.gem/ruby/2.0.0/bin
export PATH

# Enable dircolors on solarized
eval `dircolors /etc/dir_colors`

# Trackpoint scrolling
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200

# tmux 256 colors
alias tmux='tmux -2'

# ccache dir
export CCACHE_DIR=/var/cache/ccache
