# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# Default theme: ZSH_THEME="robbyrussell"
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="dd.mm.yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

#autoload -U compinit promptinit
#prompt pure

# This will set the default prompt to the walters theme
#prompt walters

# User configuration

export PATH=/usr/lib/ccache/bin:$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Ignore duplicates in history
setopt HIST_IGNORE_DUPS

export TERM=xterm-256color

# ccache dir
export CCACHE_DIR=/var/cache/ccache

# Export GOROOT
export GOROOT=/usr/lib/go
export GOPATH=$HOME/.go
export PATH="$PATH:$GOPATH/bin"

if which ruby >/dev/null && which gem >/dev/null; then
    export PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
    export GEM_HOME=$(ruby -e 'print Gem.user_dir')
fi

# Make rake work with parameters
alias rake='noglob rake'

# added by travis gem
[ -f /home/haaja/.travis/travis.sh ] && source /home/haaja/.travis/travis.sh

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"

# init rbenv
if which rbenv >/dev/null; then
    eval "$(rbenv init -)"
fi

# android-sdk
export ANDROID_HOME=/opt/android-sdk
export PATH="/opt/android-sdk/tools:/opt/android-sdk/platform-tools:$PATH"

# nodejs and npm stuff
# ====================
export PATH="$HOME/.node_modules/bin:$PATH"
export NPM_CONFIG_PREFIX="$HOME/.node_modules"

# Launch tmux automatically
# If not running interactively, do not do anything
#[[ $- != *i* ]] && return
#[[ -z "$TMUX" ]] && exec tmux
