#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

PATH=$PATH:/opt/android-sdk/tools
PATH=$PATH:$HOME/.gem/ruby/2.0.0/bin
export PATH

export TERM=xterm-256color

# Trackpoint scrolling
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200

# Autocomplete
complete -cf sudo
complete -cf man

# tmux 256 colors
alias tmux='tmux -2'

# ccache dir
export CCACHE_DIR=/var/cache/ccache
